### ISSUE TITLE
Pool fails after ORPHANED blocks :help wanted

### ISSUE THREAD

**Issue by Rndexspb** [turtlecoin/turtlecoin#94] opened 2018-03-13 11:27 UTC
so the problem is, after we got orphaned block the daemon stops with the error "core dead", so the stats stops and we mining nothing, until I restart daemon and sync last blocks.

**Comment by UNIPOOL** [comment] 2018-03-13 11:37
Hi,

I don't have the same problem, I found only Orphaned blocks even with an accurate sync. 

I have push 1MH/s for test and same problem.

I have already notify the Dev Team for check this issue.

**Comment by Rndexspb** [comment] 2018-03-13 11:43
u can check here http://turtle24.ru/#pool_blocks
most of blocks are ok, but after orphaned one pool fails... we got 2 by the week

waiting for devs =)

**Comment by CaptainMeatloaf** [comment] 2018-03-13 11:58
Running the daemon in a loop is something most of the pool ops do. Just an infinite loop in a bash script will suffice for most crashes.

There are other freezes and hangs that are being worked on, that you would need to manually restart the daemon for. I've never seen this orphaned block crashing the whole daemon bug, but we know that a lot of issues arise when a server has less-than-ideal IO (ie, on a highly loaded VPS), so it may be that.

You may ask questions about pool operation on discord, and ask to be added to the pool operators chat where we can answer many questions about pool operation.

**Comment by UNIPOOL** [comment] 2018-03-13 12:14
Hi,

I think also a VPS is bad choose, I use already Dedicated Server with SSD for be sure.

**Comment by bobbieltd** [comment] 2018-03-13 12:16
I don’t agree with Discord disscussion. We need to be public discussion so other pool owners can know the issue.
I lost quite time and money for this turtle pool. If I know them in advance, perhaps, I should be more careful and take testing measures.
Turtlecoind got problem with syncs and high rate of orphaned blocks. My pool even forked out of main chain.
At the moment, the sync seems OK but I still pay attention to it. Last time, when my pool got good sync, it was over happy and forked out.
I monitor turtle network. If the network sync is good, why does mine2gether pool sometime become 90%-100% of network ?

**Comment by UNIPOOL** [comment] 2018-03-13 12:24
I think the block time is too short for the network hashrate, too short for handle it by the blockchain.

**Comment by bobbieltd** [comment] 2018-03-13 12:27
VPS can be one of problems that caused it. But a good codes can’t cause all those issues.

**Comment by UNIPOOL** [comment] 2018-03-13 12:28
I have an idea for the block time, I don't know if it's possible and a good idea.

Maybe this is possible to increase the block time from the network hashrate for handle the problem?

**Comment by UNIPOOL** [comment] 2018-03-13 12:36
Like: ( Default Time Block  +( (MH/s * Default Time Block) / 100) ) * Random Time Luck Float between 1 to 2.

For example:

First block time:
(30 + (11 MH/s * 30) / 100)) * 1.25 = 42

Next block time:

30 + (8MH/s * 30) / 100) * 1.56 = 50.54

**Comment by CaptainMeatloaf** [comment] 2018-03-13 12:40
This is not the right place to discuss the block time. For that open an issue on the meta repo with a fully fleshed out explanation, and it can be discussed.

As for things being on discord, that just how things have turned out unfortunately. I can't say I agree with it being there, I was just telling you where to find the best support.

It would also be impractical to have everything on github, as lots of the fixes we have for the pools are changed regularly and bespoke for every server. A fix that works for me on turtlepool for example, may not work for Tim on mine2gether.

The problem if mine2gether having too much hash rate is also not a discussion for this issue. This is something regularly discussed in many cryptocurrencies, and the unfortunate truth is people always gravitate to the biggest pool, regardless of how bad it is for for the network (see suprnova and ZenCash).

**Comment by UNIPOOL** [comment] 2018-03-13 12:43
I have an example:

I have push 1MH/s with a very accurate sync. I have found some blocks before some others pools with huge hashrate, the block information can be see on Explorer and on the Pending Balance pending 10 seconds and gone. 

Can you explain me that?

**Comment by CaptainMeatloaf** [comment] 2018-03-13 12:46
I'm unfortunately not sure what the cause of your issue is, if you are using the standard forknote-pool software that we all use. Blocks disappearing I have never seen.

An orphan rate of about 5% is normal, with this block time.

**Comment by UNIPOOL** [comment] 2018-03-13 12:47
When I see their informations, I see they are not Orphaned like Orphaned No

I will try another thing, maybe this is a problem when I use add-peer and seed-node argument on remote nodes.

**Comment by CaptainMeatloaf** [comment] 2018-03-13 12:51
If it's 10 seconds it's entirely possible that the orphaned block and the re-org is being processed by your pool software and your interface has not updated yet.

Regardless, this has derailed the original issue. If you have any further issues please make your own in the appropriate location.

**Comment by bobbieltd** [comment] 2018-03-13 12:56
"A fix that works for me on turtlepool for example, may not work for Tim on mine2gether." -->For me, it's very weird with this. So we need a very specific fix for each pool.
I agree that we are out of topic here. But it's better than spamming more new issues on turtlecoin Github.
I just want to inform this new young pool owner that he can run into more other issues.

**Comment by bobbieltd** [comment] 2018-03-13 13:04
@UNIPOOL  "The block information can be see on Explorer and on the Pending Balance pending 10 seconds and gone." . There is another explanation for this, someone rewrote the blockchain and make yours invalid.

**Comment by Rndexspb** [comment] 2018-03-13 13:50
@CaptainMeatloaf it's not a vps, it's dedicated... load is ok, everything works good, but if orphaned block comes, daemon crashes, and pool accepting shares, but with NOBLOCKTEMPALATE and so on...
so is there some decision to resolve it? maybe a cron script or what?

**Comment by CaptainMeatloaf** [comment] 2018-03-13 13:56
The daemon in an infinite loop in a bash script will be fine. This issue is strange though, I've never heard of it. Are you using the latest binaries from the release page?

**Comment by Rndexspb** [comment] 2018-03-13 13:58
@CaptainMeatloaf yes i do, started pool 9 days a go i think

normal block found  2018-03-13  07:13:18
orphaned block found 2018-03-13 07:13:33 so starts **errors**:

2018-03-13 07:13:33 (Thread 1) Error polling getblocktemplate {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-03-13 07:13:34 (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:35 (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:36 (Thread 1) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:34 (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:35 (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:36 (Thread 2) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:33 (Thread 6) Error polling getblocktemplate {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
2018-03-13 07:13:34 (Thread 6) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:35 (Thread 6) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:36 (Thread 6) Error polling getblocktemplate {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
2018-03-13 07:13:33 (Thread 3) Error polling getblocktemplate {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

**Comment by CaptainMeatloaf** [comment] 2018-03-13 13:59
Those are normal pool errors when it cannot connect to the daemon.

The core dying is strange though, what version of linux are you running the server on?

**Comment by Rndexspb** [comment] 2018-03-13 14:01
@CaptainMeatloaf ubuntu server lts 16.04

**Comment by CaptainMeatloaf** [comment] 2018-03-13 14:05
The daemon runs perfectly fine on mine with the same version. Are you using the version with static libs? What flags are you running your daemon with?

**Comment by Rndexspb** [comment] 2018-03-13 14:07
@CaptainMeatloaf yes, TurtleCoind --allow-local-ip and no more flags

**Comment by CaptainMeatloaf** [comment] 2018-03-13 14:09
Then I'm unfortunately not sure what your issue with orphaned blocks crashing is. For auto-restarting your daemon a shell script with an infinite loop containing the command line for the daemon will suffice.

**Comment by Rndexspb** [comment] 2018-03-13 14:29
@CaptainMeatloaf but should i restart pool too (node init.js)?

**Comment by CaptainMeatloaf** [comment] 2018-03-13 14:30
No it will auto-reconnect once the daemon is contactable again.

**Comment by Rndexspb** [comment] 2018-03-13 14:40
@CaptainMeatloaf how do you run, what the script is, could you post it pls?

**Comment by CaptainMeatloaf** [comment] 2018-03-13 14:48
```bash
#!/bin/bash
while true
do
        ./TurtleCoind --rpc-bind-ip yourexternalip --rpc-bind-port yourrpcport --p2p-bind-port 11897 --p2p-bind-ip yourexternalip
        sleep 1
done
```

Is the command line I use. RPC port is closed off with UFW and only accessible to whitelisted IPs.

**Comment by bobbieltd** [comment] 2018-03-14 05:24
@CaptainMeatloaf Can I pose a question with your script ? Why do you bind port and ip with p2p ? I’ve never seen anyone using this with other coins.

**Comment by Rndexspb** [comment] 2018-03-14 08:28
@CaptainMeatloaf thanks

**Comment by CaptainMeatloaf** [comment] 2018-03-15 12:30
@bobbieltd I do it because I have multiple IPs assigned to some of my boxes

**Comment by bobbieltd** [comment] 2018-03-15 19:01
@CaptainMeatloaf Thanks for your help and activities with turtlecoin (even thought, you are over protective toward this coin). Turtlecoin needs more people like you.

**Closed** 2018-03-20 22:35 UTC
