### ISSUE TITLE
wallet-api sometimes fails to open or when it does it fails to make a call

### ISSUE THREAD

**Issue by dirtybits** [turtlecoin/turtlecoin#755] opened 2019-03-13 07:12 UTC
### System Information

**Operating System**: <--Antergos Linux x86_64-->
**OS Version**: 
**CPU Make, Model, & Speed**: 
**Amount of RAM**: 
**Hard Drive Type**: 
**Hard Drive Size**: 
**Volume Type**: 

### TurtleCoin Build Information

**Version:** 
**Binary Source:** 
**If self compiled, please provide all the build commands you used**
```
Please insert your build commands here. Example:
$ cmake ..
$ make -j3
```
![error1](https://user-images.githubusercontent.com/28834908/54259830-01f61b00-4535-11e9-90bc-ffb8c8e7dd2c.png)

**If self compiled, please provide of your TurtleCoin CMake output at the default verbosity**:
```
Please insert your default verbosity CMake output here:
[yogi@ironhorse build]$ cmake ..
-- FORCE_USE_HEAP: ENABLED
-- HW AES: ENABLED
-- OPTIMIZED_ARM_MULTIPLICATION: ENABLED
-- Found Git: /usr/bin/git
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Boost Found: /usr/include
-- *************************************************************************
The Crypto++ library does not officially support CMake. CMake support is a
community effort, and the library works with the folks using CMake to help
improve it. If you find an issue then please fix it or report it at
https://github.com/noloader/cryptopp-cmake.
-- *************************************************************************
-- Platform: x86_64
-- Native arch: FALSE
-- Compiler: /usr/bin/c++
-- Flags:  -std=c++17  -Wall -Wextra -Wpointer-arith -Wvla -Wwrite-strings  -Wno-error=extra -Wno-error=unused-function -Wno-error=sign-compare -Wno-error=strict-aliasing -Wno-error=type-limits -Wno-unused-parameter -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wno-error=unused-result -Wlogical-op -Wno-error=maybe-uninitialized -Wno-error=clobbered -Wno-error=unused-but-set-variable -Wno-error=odr -Wno-reorder -Wno-missing-field-initializers  -maes -pthread
-- Compiler options: 
-- Compiler definitions: CRYPTOPP_DISABLE_SSSE3;CRYPTOPP_DISABLE_SSSE4
-- Build type: RelWithDebInfo
-- Enabling RTTI in Debug builds only (default)
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yogi/testcat/catalyst/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yogi/testcat/catalyst/build

```

### Issue Report

**Binary Reported:** 

#### Steps to Reproduce

1.  
2. 
3. 
4.

**Comment by brandonlehmann** [comment] 2019-03-13 12:15
Based on discord chat this is a duplicate of #710

**Closed by brandonlehmann** 2019-03-13 12:15 UTC
