### ISSUE TITLE
Segfault at UPGRADE_HEIGHT_V5

### ISSUE THREAD

**Issue by atomsett** [turtlecoin/turtlecoin#536] opened 2018-10-06 14:24 UTC
Daemon segfaults at UPGRADE_HEIGHT_V5

### System Information

**Operating System**: Ubuntu 18.04 LTS
**OS Version**: 4.15.0-34-generic #37-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
**CPU Make, Model, & Speed**: Ryzen 2700X @1.3GHz
**Amount of RAM**: 8GB
**Hard Drive Type**: WD GREEN SATA SSD
**Hard Drive Size**: 120GB
**Volume Type**: ext4

### TurtleCoin Build Information

**Version:** : v0.8.4.1276
**Binary Source:** self-compiled
```
mkdir build && cd build
cmake ..
make -j12
```
cmake output:
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Git: /usr/bin/git
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   chrono
--   regex
--   serialization
--   program_options
--   atomic
-- Boost Found: /usr/include
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Enabling RTTI in Debug builds only (default)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- JNI library is disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /turtlecoin/build/rocksdb
-- Configuring done
-- Generating done
-- Build files have been written to: /turtlecoin/build
```

### Issue Report

**Binary Reported:** : TurtleCoind

#### Expected Behavior

Chain upgrade to V5

#### Current Behavior

Segfault adding block

##### Screen Shots

![v5_segfault](https://user-images.githubusercontent.com/42898566/46572254-9226a780-c97a-11e8-8680-f21d49340f95.png)

#### Steps to Reproduce

1. Clone repo:
`git clone --single-branch --branch soft_shell https://github.com/turtlecoin/turtlecoin.git`

2. Edit CryptoNoteConfig.h to adjust blockchain upgrade heights @ line 143+
```
const uint32_t UPGRADE_HEIGHT_V2                             = 1;
const uint32_t UPGRADE_HEIGHT_V3                             = 2;
const uint32_t UPGRADE_HEIGHT_V4                             = 10;
const uint32_t UPGRADE_HEIGHT_V5                             = 20;
const uint32_t UPGRADE_HEIGHT_CURRENT               = UPGRADE_HEIGHT_V5; 
```
3. Modify CRYPTONOTE_NETWORK bytes to avoid any issues while testing:
`{  0xaa, 0x0c, ..`

4. Remove seed nodes entirely as we can reproduce this problem with `./Turtlecoind --testnet --data-dir testnet`

#### Possible Solution
Sooory, no solution found *yet*.

**Comment by brandonlehmann** [comment] 2018-10-06 14:34
—testnet is unsupported. 

I ran this branch without issue just yesterday.

I notice you didn’t say you changed the default checkpoints as well. 

Which order did you start your daemons up in?

**Comment by atomsett** [comment] 2018-10-06 14:43
Actually true I hadn't edited the checkpoints on this occasion.
However, I reproduced this error this morning from our own fork, which definitely did - same result
In fact same result running with the tesnet flag or not - same segfaulting
In my 'live testnet' last night I started Daemon1 and 2 on VPS servers
Following that I started my local daemon
Finally, I started the miner binary and began mining.

**Comment by brandonlehmann** [comment] 2018-10-06 14:50
Run this in the binary folder and paste back the results please. 

`cryptotest 0100fb8e8ac805899323371bb790db19218afd8db8e3755d8b90f39b3d5506a9abce4fa912244500000000ee8146d49fa93ee724deb57d12cbc6c6f3b924d946127c7a97418f9348828f0f02`

**Comment by atomsett** [comment] 2018-10-06 14:51
```
./cryptotest 0100fb8e8ac805899323371bb790db19218afd8db8e3755d8b90f39b3d5506a9abce4fa912244500000000ee8146d49fa93ee724deb57d12cbc6c6f3b924d946127c7a97418f9348828f0f02

Input: 0100fb8e8ac805899323371bb790db19218afd8db8e3755d8b90f39b3d5506a9abce4fa912244500000000ee8146d49fa93ee724deb57d12cbc6c6f3b924d946127c7a97418f9348828f0f02

cn_fast_hash: b542df5b6e7f5f05275c98e7345884e2ac726aeeb07e03e44e0389eb86cd05f0
cn_slow_hash_v0: 1b606a3f4a07d6489a1bcd07697bd16696b61c8ae982f61a90160f4e52828a7f
cn_slow_hash_v1: c9fae8425d8688dc236bcdbc42fdb42d376c6ec190501aa84b04a4b4cf1ee122
cn_lite_slow_hash_v0: 28a22bad3f93d1408fca472eb5ad1cbe75f21d053c8ce5b3af105a57713e21dd
cn_lite_slow_hash_v1: 87c4e570653eb4c2b42b7a0d546559452dfab573b82ec52f152b7ff98e79446f

cn_soft_shell_slow_hash_v0 (0): 546c3f1badd7c1232c7a3b88cdb013f7f611b7bd3d1d2463540fccbd12997982
cn_soft_shell_slow_hash_v0 (512): 54b7350dd54e73e533ab4012835eec0e2468b01f432822352fd60e9fef70ba4e
cn_soft_shell_slow_hash_v0 (1024): a25c8be1e6b4f2696163a5f6852b6bfdd9eabc442bc8bb992ff8aea89a546f9f
cn_soft_shell_slow_hash_v0 (1536): c8c4b871cefd49fb8bc4ecd77c9687ec148eeed2180d0f80b002a9de1f509c18
cn_soft_shell_slow_hash_v0 (2048): 6eae70222ff2121bff32764cb606a6565f10e2fe87a8467ef547d1d271cbfbbd
cn_soft_shell_slow_hash_v0 (2560): c8c4b871cefd49fb8bc4ecd77c9687ec148eeed2180d0f80b002a9de1f509c18
cn_soft_shell_slow_hash_v0 (3072): a25c8be1e6b4f2696163a5f6852b6bfdd9eabc442bc8bb992ff8aea89a546f9f
cn_soft_shell_slow_hash_v0 (3584): 54b7350dd54e73e533ab4012835eec0e2468b01f432822352fd60e9fef70ba4e
cn_soft_shell_slow_hash_v0 (4096): 546c3f1badd7c1232c7a3b88cdb013f7f611b7bd3d1d2463540fccbd12997982
cn_soft_shell_slow_hash_v0 (4608): 54b7350dd54e73e533ab4012835eec0e2468b01f432822352fd60e9fef70ba4e
cn_soft_shell_slow_hash_v0 (5120): a25c8be1e6b4f2696163a5f6852b6bfdd9eabc442bc8bb992ff8aea89a546f9f
cn_soft_shell_slow_hash_v0 (5632): c8c4b871cefd49fb8bc4ecd77c9687ec148eeed2180d0f80b002a9de1f509c18
cn_soft_shell_slow_hash_v0 (6144): 6eae70222ff2121bff32764cb606a6565f10e2fe87a8467ef547d1d271cbfbbd
cn_soft_shell_slow_hash_v0 (6656): c8c4b871cefd49fb8bc4ecd77c9687ec148eeed2180d0f80b002a9de1f509c18
cn_soft_shell_slow_hash_v0 (7168): a25c8be1e6b4f2696163a5f6852b6bfdd9eabc442bc8bb992ff8aea89a546f9f
cn_soft_shell_slow_hash_v0 (7680): 54b7350dd54e73e533ab4012835eec0e2468b01f432822352fd60e9fef70ba4e
cn_soft_shell_slow_hash_v0 (8192): 546c3f1badd7c1232c7a3b88cdb013f7f611b7bd3d1d2463540fccbd12997982

cn_soft_shell_slow_hash_v1 (0): 29e7831780a0ab930e0fe3b965f30e8a44d9b3f9ad2241d67cfbfea3ed62a64e
cn_soft_shell_slow_hash_v1 (512): 702c3eb285452dbfce53c17da2c0d309769194880e8c3d4f0c5787efcf055f2f
cn_soft_shell_slow_hash_v1 (1024): 91f2255c59ecb66fc9fd2ec76c0f385e79fa18d22802c7d426c312af00ebaecf
cn_soft_shell_slow_hash_v1 (1536): c81bd0e073c0a35cb2921c0ddf24fd951808fceff572d459685240dda78939ed
cn_soft_shell_slow_hash_v1 (2048): ebd1c981c4fb1c0085b7ab28ec164afa2290f079ad5dcffd017976a19700590f
cn_soft_shell_slow_hash_v1 (2560): c81bd0e073c0a35cb2921c0ddf24fd951808fceff572d459685240dda78939ed
cn_soft_shell_slow_hash_v1 (3072): 91f2255c59ecb66fc9fd2ec76c0f385e79fa18d22802c7d426c312af00ebaecf
cn_soft_shell_slow_hash_v1 (3584): 702c3eb285452dbfce53c17da2c0d309769194880e8c3d4f0c5787efcf055f2f
cn_soft_shell_slow_hash_v1 (4096): 29e7831780a0ab930e0fe3b965f30e8a44d9b3f9ad2241d67cfbfea3ed62a64e
cn_soft_shell_slow_hash_v1 (4608): 702c3eb285452dbfce53c17da2c0d309769194880e8c3d4f0c5787efcf055f2f
cn_soft_shell_slow_hash_v1 (5120): 91f2255c59ecb66fc9fd2ec76c0f385e79fa18d22802c7d426c312af00ebaecf
cn_soft_shell_slow_hash_v1 (5632): c81bd0e073c0a35cb2921c0ddf24fd951808fceff572d459685240dda78939ed
cn_soft_shell_slow_hash_v1 (6144): ebd1c981c4fb1c0085b7ab28ec164afa2290f079ad5dcffd017976a19700590f
cn_soft_shell_slow_hash_v1 (6656): c81bd0e073c0a35cb2921c0ddf24fd951808fceff572d459685240dda78939ed
cn_soft_shell_slow_hash_v1 (7168): 91f2255c59ecb66fc9fd2ec76c0f385e79fa18d22802c7d426c312af00ebaecf
cn_soft_shell_slow_hash_v1 (7680): 702c3eb285452dbfce53c17da2c0d309769194880e8c3d4f0c5787efcf055f2f
cn_soft_shell_slow_hash_v1 (8192): 29e7831780a0ab930e0fe3b965f30e8a44d9b3f9ad2241d67cfbfea3ed62a64e
```

**Comment by brandonlehmann** [comment] 2018-10-06 14:54
It’s not the crypto that’s segfaulting then. Something else has to be wrong with your edits. If it was the algo throwing fits that would have segfaulted or just died as well.

**Comment by atomsett** [comment] 2018-10-06 14:59
That's why I took the TC code and only changed the details listed above.  I appreciate you tested this last night, but I assume your V5 upgrade height was still set to 2000000?
Would I be correct in my assumption, that the soft shell code is not active until that block height?

**Comment by brandonlehmann** [comment] 2018-10-06 16:06
Also... here https://gist.github.com/brandonlehmann/6b49c84bc5fdc93e840437397cfa9069

**Comment by brandonlehmann** [comment] 2018-10-06 18:44
@atomsett  See the necessary testnet changes at https://github.com/brandonlehmann/turtlecoin/commit/801396b63e3389409833b63028709a44c39095c6 to verify you've got them all

**Comment by atomsett** [comment] 2018-10-06 19:09
having a look now, thanks for your help...

**Comment by atomsett** [comment] 2018-10-07 04:16
compiled boost v1.59 and compiled with that - same result.
compiled on a fresh install of ubuntu 18.04 running on AMD Opteron - same result
CryptoNoteConfig.h:
```
// Copyright (c) 2012-2017, The CryptoNote developers, The Bytecoin developers
// Copyright (c) 2014-2018, The Monero Project
// Copyright (c) 2018, The TurtleCoin Developers
//
// Please see the included LICENSE file for more information.

#pragma once

#include <cstddef>
#include <cstdint>
#include <limits>
#include <initializer_list>
#include <boost/uuid/uuid.hpp>

namespace CryptoNote {
namespace parameters {

const uint64_t DIFFICULTY_TARGET                             = 30; // seconds

const uint32_t CRYPTONOTE_MAX_BLOCK_NUMBER                   = 500000000;
const size_t   CRYPTONOTE_MAX_BLOCK_BLOB_SIZE                = 500000000;
const size_t   CRYPTONOTE_MAX_TX_SIZE                        = 1000000000;
const uint64_t CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX       = 3914525;
const uint32_t CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW          = 40;
const uint64_t CRYPTONOTE_BLOCK_FUTURE_TIME_LIMIT            = 60 * 60 * 2;
const uint64_t CRYPTONOTE_BLOCK_FUTURE_TIME_LIMIT_V3         = 3 * DIFFICULTY_TARGET;
const uint64_t CRYPTONOTE_BLOCK_FUTURE_TIME_LIMIT_V4         = 6 * DIFFICULTY_TARGET;

const size_t   BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW             = 60;
const size_t   BLOCKCHAIN_TIMESTAMP_CHECK_WINDOW_V3          = 11;

// MONEY_SUPPLY - total number coins to be generated
const uint64_t MONEY_SUPPLY                                  = UINT64_C(100000000000000);
const uint32_t ZAWY_DIFFICULTY_BLOCK_INDEX                   = 187000;
const size_t ZAWY_DIFFICULTY_V2                              = 0;
const uint8_t ZAWY_DIFFICULTY_DIFFICULTY_BLOCK_VERSION       = 3;

const uint64_t LWMA_2_DIFFICULTY_BLOCK_INDEX                 = 620000;
const uint64_t LWMA_2_DIFFICULTY_BLOCK_INDEX_V2              = 700000;
const uint64_t LWMA_2_DIFFICULTY_BLOCK_INDEX_V3              = 800000;

const uint64_t DIFFICULTY_WINDOW_V3                          = 60;
const uint64_t DIFFICULTY_BLOCKS_COUNT_V3                    = DIFFICULTY_WINDOW_V3 + 1;

const unsigned EMISSION_SPEED_FACTOR                         = 25;
static_assert(EMISSION_SPEED_FACTOR <= 8 * sizeof(uint64_t), "Bad EMISSION_SPEED_FACTOR");

/* Premine amount */
const uint64_t GENESIS_BLOCK_REWARD                          = UINT64_C(0);

/* How to generate a premine:

* Compile your code

* Run zedwallet, ignore that it can't connect to the daemon, and generate an
  address. Save this and the keys somewhere safe.

* Launch the daemon with these arguments:
--print-genesis-tx --genesis-block-reward-address <premine wallet address>

For example:
TurtleCoind --print-genesis-tx --genesis-block-reward-address TRTLv2Fyavy8CXG8BPEbNeCHFZ1fuDCYCZ3vW5H5LXN4K2M2MHUpTENip9bbavpHvvPwb4NDkBWrNgURAd5DB38FHXWZyoBh4wW

* Take the hash printed, and replace it with the hash below in GENESIS_COINBASE_TX_HEX

* Recompile, setup your seed nodes, and start mining

* You should see your premine appear in the previously generated wallet.

*/
const char     GENESIS_COINBASE_TX_HEX[]                     = "012801ff000100022b8b42bd94914de2f56f2c5bc870952400d6fcd642963eee7a4d0d199dab70b221013c0cd59d7a993ad2d2861a6aae8558c26bec9b023d0a6ec09f3b34df4f499954";

/* This is the unix timestamp of the first "mined" block (technically block 2, not the genesis block)
   You can get this value by doing "print_block 2" in TurtleCoind. It is used to know what timestamp
   to import from when the block height cannot be found in the node or the node is offline. */
const uint64_t GENESIS_BLOCK_TIMESTAMP                       = 1512800692;

const size_t   CRYPTONOTE_REWARD_BLOCKS_WINDOW               = 100;
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE     = 100000; //size of block (bytes) after which reward for block calculated using block size
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V2  = 20000;
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_V1  = 10000;
const size_t   CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_CURRENT = CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE;
const size_t   CRYPTONOTE_COINBASE_BLOB_RESERVED_SIZE        = 600;
const size_t   CRYPTONOTE_DISPLAY_DECIMAL_POINT              = 2;
const uint64_t MINIMUM_FEE                                   = UINT64_C(10);

const uint64_t MINIMUM_MIXIN_V1                              = 0;
const uint64_t MAXIMUM_MIXIN_V1                              = 100;

const uint64_t MINIMUM_MIXIN_V2                              = 7;
const uint64_t MAXIMUM_MIXIN_V2                              = 7;

const uint64_t MINIMUM_MIXIN_V3                              = 3;
const uint64_t MAXIMUM_MIXIN_V3                              = 3;

/* The heights to activate the mixin limits at */
const uint32_t MIXIN_LIMITS_V1_HEIGHT                        = 440000;
const uint32_t MIXIN_LIMITS_V2_HEIGHT                        = 620000;
const uint32_t MIXIN_LIMITS_V3_HEIGHT                        = 800000;

/* The mixin to use by default with zedwallet and turtle-service */
/* DEFAULT_MIXIN_V0 is the mixin used before MIXIN_LIMITS_V1_HEIGHT is started */
const uint64_t DEFAULT_MIXIN_V0                              = 3;
const uint64_t DEFAULT_MIXIN_V1                              = MAXIMUM_MIXIN_V1;
const uint64_t DEFAULT_MIXIN_V2                              = MAXIMUM_MIXIN_V2;
const uint64_t DEFAULT_MIXIN_V3                              = MAXIMUM_MIXIN_V3;

const uint64_t DEFAULT_DUST_THRESHOLD                        = UINT64_C(10);
const uint64_t DEFAULT_DUST_THRESHOLD_V2                     = UINT64_C(0);

const uint32_t DUST_THRESHOLD_V2_HEIGHT                      = MIXIN_LIMITS_V2_HEIGHT;
const uint32_t FUSION_DUST_THRESHOLD_HEIGHT_V2               = 800000;

const uint64_t EXPECTED_NUMBER_OF_BLOCKS_PER_DAY             = 24 * 60 * 60 / DIFFICULTY_TARGET;
const size_t   DIFFICULTY_WINDOW                             = 17;
const size_t   DIFFICULTY_WINDOW_V1                          = 2880;
const size_t   DIFFICULTY_WINDOW_V2                          = 2880;
const size_t   DIFFICULTY_CUT                                = 0;  // timestamps to cut after sorting
const size_t   DIFFICULTY_CUT_V1                             = 60;
const size_t   DIFFICULTY_CUT_V2                             = 60;
const size_t   DIFFICULTY_LAG                                = 0;  // !!!
const size_t   DIFFICULTY_LAG_V1                             = 15;
const size_t   DIFFICULTY_LAG_V2                             = 15;
static_assert(2 * DIFFICULTY_CUT <= DIFFICULTY_WINDOW - 2, "Bad DIFFICULTY_WINDOW or DIFFICULTY_CUT");

const size_t   MAX_BLOCK_SIZE_INITIAL                        = 100000;
const uint64_t MAX_BLOCK_SIZE_GROWTH_SPEED_NUMERATOR         = 100 * 1024;
const uint64_t MAX_BLOCK_SIZE_GROWTH_SPEED_DENOMINATOR       = 365 * 24 * 60 * 60 / DIFFICULTY_TARGET;
const uint64_t MAX_EXTRA_SIZE                                = 140000;

const uint64_t CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS     = 1;
const uint64_t CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_SECONDS    = DIFFICULTY_TARGET * CRYPTONOTE_LOCKED_TX_ALLOWED_DELTA_BLOCKS;

const uint64_t CRYPTONOTE_MEMPOOL_TX_LIVETIME                = 60 * 60 * 24;     //seconds, one day
const uint64_t CRYPTONOTE_MEMPOOL_TX_FROM_ALT_BLOCK_LIVETIME = 60 * 60 * 24 * 7; //seconds, one week
const uint64_t CRYPTONOTE_NUMBER_OF_PERIODS_TO_FORGET_TX_DELETED_FROM_POOL = 7;  // CRYPTONOTE_NUMBER_OF_PERIODS_TO_FORGET_TX_DELETED_FROM_POOL * CRYPTONOTE_MEMPOOL_TX_LIVETIME = time to forget tx

const size_t   FUSION_TX_MAX_SIZE                            = CRYPTONOTE_BLOCK_GRANTED_FULL_REWARD_ZONE_CURRENT * 30 / 100;
const size_t   FUSION_TX_MIN_INPUT_COUNT                     = 12;
const size_t   FUSION_TX_MIN_IN_OUT_COUNT_RATIO              = 4;

const uint32_t KEY_IMAGE_CHECKING_BLOCK_INDEX                = 0;
const uint32_t UPGRADE_HEIGHT_V2                             = 1;
const uint32_t UPGRADE_HEIGHT_V3                             = 2;
const uint32_t UPGRADE_HEIGHT_V4                             = 3; // Upgrade height for CN-Lite Variant 1 switch.
const uint32_t UPGRADE_HEIGHT_V5                             = 4; // Upgrade height for CN-Soft Shell switch
const uint32_t UPGRADE_HEIGHT_CURRENT                        = UPGRADE_HEIGHT_V5; 
const unsigned UPGRADE_VOTING_THRESHOLD                      = 90;               // percent
const uint32_t UPGRADE_VOTING_WINDOW                         = EXPECTED_NUMBER_OF_BLOCKS_PER_DAY;  // blocks
const uint32_t UPGRADE_WINDOW                                = EXPECTED_NUMBER_OF_BLOCKS_PER_DAY;  // blocks
static_assert(0 < UPGRADE_VOTING_THRESHOLD && UPGRADE_VOTING_THRESHOLD <= 100, "Bad UPGRADE_VOTING_THRESHOLD");
static_assert(UPGRADE_VOTING_WINDOW > 1, "Bad UPGRADE_VOTING_WINDOW");

/* Block heights we are going to have hard forks at */
const uint64_t FORK_HEIGHTS[] =
{
    1,
    2,
    3,
    4
};

/* MAKE SURE TO UPDATE THIS VALUE WITH EVERY MAJOR RELEASE BEFORE A FORK */
const uint64_t SOFTWARE_SUPPORTED_FORK_INDEX                 = 3;

const uint64_t FORK_HEIGHTS_SIZE = sizeof(FORK_HEIGHTS) / sizeof(*FORK_HEIGHTS);

/* The index in the FORK_HEIGHTS array that this version of the software will
   support. For example, if CURRENT_FORK_INDEX is 3, this version of the
   software will support the fork at 600,000 blocks.

   This will default to zero if the FORK_HEIGHTS array is empty, so you don't
   need to change it manually. */
const uint8_t CURRENT_FORK_INDEX = FORK_HEIGHTS_SIZE == 0 ? 0 : SOFTWARE_SUPPORTED_FORK_INDEX;

static_assert(CURRENT_FORK_INDEX >= 0, "CURRENT FORK INDEX must be >= 0");
/* Make sure CURRENT_FORK_INDEX is a valid index, unless FORK_HEIGHTS is empty */
static_assert(FORK_HEIGHTS_SIZE == 0 || CURRENT_FORK_INDEX < FORK_HEIGHTS_SIZE, "CURRENT_FORK_INDEX out of range of FORK_HEIGHTS!");

const char     CRYPTONOTE_BLOCKS_FILENAME[]                  = "blocks.bin";
const char     CRYPTONOTE_BLOCKINDEXES_FILENAME[]            = "blockindexes.bin";
const char     CRYPTONOTE_POOLDATA_FILENAME[]                = "poolstate.bin";
const char     P2P_NET_DATA_FILENAME[]                       = "p2pstate.bin";
const char     MINER_CONFIG_FILE_NAME[]                      = "miner_conf.json";
} // parameters

const char     CRYPTONOTE_NAME[]                             = "TurtleCoinSS";

const uint8_t  TRANSACTION_VERSION_1                         =  1;
const uint8_t  TRANSACTION_VERSION_2                         =  2;
const uint8_t  CURRENT_TRANSACTION_VERSION                   =  TRANSACTION_VERSION_1;
const uint8_t  BLOCK_MAJOR_VERSION_1                         =  1;
const uint8_t  BLOCK_MAJOR_VERSION_2                         =  2;
const uint8_t  BLOCK_MAJOR_VERSION_3                         =  3;
const uint8_t  BLOCK_MAJOR_VERSION_4                         =  4;
const uint8_t  BLOCK_MAJOR_VERSION_5                         =  5;
const uint8_t  BLOCK_MINOR_VERSION_0                         =  0;
const uint8_t  BLOCK_MINOR_VERSION_1                         =  1;

const size_t   BLOCKS_IDS_SYNCHRONIZING_DEFAULT_COUNT        =  10000;  //by default, blocks ids count in synchronizing
const size_t   BLOCKS_SYNCHRONIZING_DEFAULT_COUNT            =  100;    //by default, blocks count in blocks downloading
const size_t   COMMAND_RPC_GET_BLOCKS_FAST_MAX_COUNT         =  1000;

const int      P2P_DEFAULT_PORT                              =  21018;
const int      RPC_DEFAULT_PORT                              =  31018;
const int      SERVICE_DEFAULT_PORT                          =  8070;

const size_t   P2P_LOCAL_WHITE_PEERLIST_LIMIT                =  1000;
const size_t   P2P_LOCAL_GRAY_PEERLIST_LIMIT                 =  5000;

// P2P Network Configuration Section - This defines our current P2P network version
// and the minimum version for communication between nodes
const uint8_t  P2P_CURRENT_VERSION                           = 3;
const uint8_t  P2P_MINIMUM_VERSION                           = 2;
// This defines the number of versions ahead we must see peers before we start displaying
// warning messages that we need to upgrade our software.
const uint8_t  P2P_UPGRADE_WINDOW                            = 2;

const size_t   P2P_CONNECTION_MAX_WRITE_BUFFER_SIZE          = 32 * 1024 * 1024; // 32 MB
const uint32_t P2P_DEFAULT_CONNECTIONS_COUNT                 = 8;
const size_t   P2P_DEFAULT_WHITELIST_CONNECTIONS_PERCENT     = 70;
const uint32_t P2P_DEFAULT_HANDSHAKE_INTERVAL                = 60;            // seconds
const uint32_t P2P_DEFAULT_PACKET_MAX_SIZE                   = 50000000;      // 50000000 bytes maximum packet size
const uint32_t P2P_DEFAULT_PEERS_IN_HANDSHAKE                = 250;
const uint32_t P2P_DEFAULT_CONNECTION_TIMEOUT                = 5000;          // 5 seconds
const uint32_t P2P_DEFAULT_PING_CONNECTION_TIMEOUT           = 2000;          // 2 seconds
const uint64_t P2P_DEFAULT_INVOKE_TIMEOUT                    = 60 * 2 * 1000; // 2 minutes
const size_t   P2P_DEFAULT_HANDSHAKE_INVOKE_TIMEOUT          = 5000;          // 5 seconds
const char     P2P_STAT_TRUSTED_PUB_KEY[]                    = "";

const char     LATEST_VERSION_URL[]                          = "http://latest.turtlecoin.lol";
const static   boost::uuids::uuid CRYPTONOTE_NETWORK         =
{
    {  0xb5, 0x0c, 0x4a, 0x6c, 0xcf, 0x52, 0x57, 0x41, 0x65, 0xf9, 0x91, 0xa4, 0xb6, 0xc1, 0x43, 0xba  }
};

const char* const SEED_NODES[] = {
  "35.204.115.139:21018",//
  "35.242.151.134:21018", //
  "127.0.0.1:21018", //
  "127.0.0.1:11018", //
  "127.0.0.1:10018"
};
} // CryptoNote
```
Screenshot of latest test running 2x remote daemons, 1 local. Can crash local and remote daemons:
![segfault1](https://user-images.githubusercontent.com/42898566/46578161-02234500-c9f0-11e8-97dc-125a76d2a9b8.png)

What else should I try?  Ubuntu 16.04?

**Comment by brandonlehmann** [comment] 2018-10-07 14:07
You continually mislead me... that clearly has additional changes applied from the base...

**Comment by brandonlehmann** [comment] 2018-10-07 14:33
Okay... I've managed to replicate this on *nix took quite a bit of work... hence the reason SS is a WIP :)

**Comment by brandonlehmann** [comment] 2018-10-07 14:41
I've got some ideas where it's going side ways. Might take a little bit to work through.

**Comment by brandonlehmann** [comment] 2018-10-07 15:36
I know where the issue is for sure. I should have it fixed in the next 12h.

**Comment by brandonlehmann** [comment] 2018-10-07 22:10
Updated code coming shortly -- doing some quick testing now.

**Comment by brandonlehmann** [comment] 2018-10-07 22:36
@atomsett try this one https://github.com/turtlecoin/turtlecoin/tree/soft_shell

**Comment by brandonlehmann** [comment] 2018-10-07 23:07
My tests are showing that this is proceeding well. No more crash conditions :)

**Comment by Amity-Core** [comment] 2018-10-07 23:07
I'm just gunna test it out, cheers for working on this dude!

**Comment by brandonlehmann** [comment] 2018-10-08 01:57
We good?

**Comment by atomsett** [comment] 2018-10-08 04:40
![pow_too_weak](https://user-images.githubusercontent.com/42898566/46592608-6d3a4d80-cabc-11e8-97cb-3d4b60bda821.png)
Using the same instructions given, I am seeing "Proof of work too weak for block 5" error.  Can you help me fix this, please?

**Comment by brandonlehmann** [comment] 2018-10-08 15:50
![image](https://user-images.githubusercontent.com/20562132/46619488-3716c100-caf0-11e8-9af4-cecc4184503a.png)
![image](https://user-images.githubusercontent.com/20562132/46619512-4269ec80-caf0-11e8-9e95-a8d62fcaace4.png)
![image](https://user-images.githubusercontent.com/20562132/46619540-4f86db80-caf0-11e8-9ff0-b3a9477653ae.png)

**Comment by brandonlehmann** [comment] 2018-10-08 18:39
Confirmed clean fork works. @rashedmyt 

Still running testnet using https://github.com/brandonlehmann/turtlecoin/tree/soft_shell_test if anyone else wants to check.

**Closed by brandonlehmann** 2018-10-08 18:39 UTC
