### ISSUE TITLE
wallet-upgrader needs further scrutiny

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin#943] opened 2019-11-22 16:23 UTC
A few users have reported the wallet-upgrader resulting in their balances doubling. I may be wrong on this, but I think they were all windows users. Potentially the file format differs slightly between OS's? Further investigation is required, as I did not experience this when testing in Linux.

**Comment by ngeojiajun** [comment] 2019-12-24 03:54
Based on my observation, after i upgrade my wallets i need to resync it in order to make it works. It that possible the cause for this problem?

**Comment by zpalmtree** [comment] 2019-12-24 11:52
> Based on my observation, after i upgrade my wallets i need to resync it in order to make it works. It that possible the cause for this problem?

Can you clarify - does the wallet automatically resync, or do you resync to fix the balance issue? The wallet upgrader is intended to allow users to retain their sync progress.

**Comment by ngeojiajun** [comment] 2019-12-24 12:11
For example, i imported keys and start syncing from block X when creating the old wallet file. Ofcourse, when i synced the wallet at Y it will have the inputs A1 and used images B1. In upgrading process, the new wallet file will have the all the keys X, A1, B1. But for unknown reason, the backend sync from X instead of Y. Through this sync it will have a new set of inputs and images, A2 and B2.
My hypothesis is if the A3=A1+A2 and B3=B1+B2 with A3 and B3 is the keys and images saved, then the balance will become A3-B3=(A1+A2)-(B1+B2)=2(A-B) if A1=A2 and B1=B2

**Comment by zpalmtree** [comment] 2020-01-27 16:00
After some further investigation by @brandonlehmann , it appears that the issue is arising is because WalletBackend starts syncing from a lower height than it is intended to - possibly because it is using the scan height rather than the block hash checkpoints.

This results in the same transactions being scanned twice, and while the backend does not add duplicate transactions, it will add duplicate inputs. We should probably be able to quickly patch this bug by not adding inputs twice, but the better fix is to figure out why it's not syncing from the correct height.

**Comment by brandonlehmann** [comment] 2020-07-31 11:51
With the sunset of WalletGreen in it's entirety in v1.0.0 and v0.28.0 being the last release to contain turtle-service the next release won't have the tools or mechanisms to upgrade from the WalletGreen format. I believe this issue can be closed as a result.

**Closed by brandonlehmann** 2020-07-31 11:51 UTC
Labels: BUG
