### ISSUE TITLE
[BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error

### ISSUE THREAD

**Issue by khunpoum** [turtlecoin/turtlecoin#44] opened 2018-02-06 21:07 UTC
ver relese v 0.3.1

after some time run simplewallet iam receiving errors but TurtleCoind is working.
and mee some time need to restart TurtleCoind and simplewallet.

how it can be fix?

simplewallet stdout:
```
2018-Feb-07 00:02:18.535571 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error
2018-Feb-07 00:02:33.510404 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error
2018-Feb-07 00:02:43.519390 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error
2018-Feb-07 00:02:58.523518 ERROR   [BlockchainSynchronizer] Failed to query blocks: NodeErrorCategory:5, Internal node error
```

```
$ uname -a
Linux trtl-pool-1 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ uname -r
4.4.0-87-generic

$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by llawwehttam** [comment] 2018-02-06 22:38
I believe this is a duplicate of:  https://github.com/turtlecoin/meta/issues/35

This is probably the right place for this issue now.

**Comment by RocksteadyTC** [comment] 2018-02-09 03:35
This needs to be solved. High priority. 2MM bounty for a fix in 48hrs.

**Comment by MoonMoonDogo** [comment] 2018-02-09 12:35
I checked my ``simplewallet.log`` but could not find the error message. Could it be that this issue is only reproducible on Linux / MacOS?
I've used version ``0.2.2`` and ``0.3.1`` of simplewallet for several weeks (on Windows 10 Pro N x64).

**Comment by MoonMoonDogo** [comment] 2018-02-09 13:40
I looked at the logs from ``Turtle?#3684`` with trace log level, and this is what I found out:

The log reveals that a RPC request fails:
```
[...]
2018-Feb-06 17:50:25.474657 TRACE   [NodeRpcProxy] queryblockslite.bin failed: NodeErrorCategory:5, Internal node error
[...]
```

Searching the code shows that the log message comes from this [line](https://github.com/turtlecoin/turtlecoin/blob/a7c267f3ca32624017a634d11b8513d82701832d/src/NodeRpcProxy/NodeRpcProxy.cpp#L585):
```cpp
  m_logger(TRACE) << "Send queryblockslite.bin request, timestamp " << req.timestamp;
  std::error_code ec = binaryCommand("/queryblockslite.bin", req, rsp);
  if (ec) {
    m_logger(TRACE) << "queryblockslite.bin failed: " << ec << ", " << ec.message();
    return ec;
  }
```

Looking at the daemon side, there is one place where ``Core::queryBlocksLite`` is called from, that is [InProcessNode::doQueryBlocksLite](https://github.com/turtlecoin/turtlecoin/blob/a7c267f3ca32624017a634d11b8513d82701832d/src/InProcessNode/InProcessNode.cpp#L687):
```cpp
std::error_code InProcessNode::doQueryBlocksLite(std::vector<Crypto::Hash>&& knownBlockIds, uint64_t timestamp,
                                                 std::vector<BlockShortEntry>& newBlocks, uint32_t& startHeight) {
  uint32_t currentHeight, fullOffset;
  std::vector<CryptoNote::BlockShortInfo> entries;

  if (!core.queryBlocksLite(knownBlockIds, timestamp, startHeight, currentHeight, fullOffset, entries)) {
    return make_error_code(CryptoNote::error::INTERNAL_NODE_ERROR);
  }
[...]
```

So ``core.queryBlocksLite`` has to return false in order to produce the logged error we see.
Looking at [core.queryBlocksLite](https://github.com/turtlecoin/turtlecoin/blob/49ca77c3c309375c69ae5261950f8fff9bd258c0/src/CryptoNoteCore/Core.cpp#L455), there is only one path where false is returned and that is when an exception is thrown:
```cpp
bool Core::queryBlocksLite(const std::vector<Crypto::Hash>& knownBlockHashes, uint64_t timestamp, uint32_t& startIndex,
                           uint32_t& currentIndex, uint32_t& fullOffset, std::vector<BlockShortInfo>& entries) const {
  assert(entries.empty());
  assert(!chainsLeaves.empty());
  assert(!chainsStorage.empty());

  throwIfNotInitialized();

  try {
[...]
  } catch (std::exception&) {
    // TODO log
    return false;
  }
```

Unfortunately, the exception thrown is not logged, although it could provide useful information why we see this error.

I propose that we add logging in the catch block in ``Core::queryBlocksLite`` so that we see what the cause of the error is. The binary with logging can then be run by anyone who can reproduce the error.
Another way would be that one attaches a debugger and breaks when an exception is thrown. This would reveal more than just logging the message but requires that the person debugging can reproduce the bug.

**Comment by SoreGums** [comment] 2018-02-09 14:15
So if I install visual studio is it fairly simple to load the code and run from inside vs? My only experiences with that kind of dev is from way back in 2004 or so when I was learning OO via Java/Eclipse. Since then it's been a text editor cause php, ruby, node, elixir :)

I'm guessing it is, I'll download it all and spin it up when I get home in an hour. Looks like you might be online then @moonmoondogo, will ping #dev_general if I get stuck find anything

**Comment by MoonMoonDogo** [comment] 2018-02-09 18:27
Summing up the findings and discussions from #dev-general:
@deertacos added logging for the exception in his [fork](https://github.com/deertacos/turtlecoin/tree/internal_node_error) and could reproduce the issue, which lead to the following log messages:
```
2018-Feb-09 11:10:52.754898 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
```

@nnamon shared his conjecture:
```
could it be those blocks that have very odd timestamps
timestamps that give a timing before the last block
they show up as (x minutes later) instead of (x seconds ago) on my block tracking scripts
```

The following [lines of code](https://github.com/turtlecoin/turtlecoin/blob/49ca77c3c309375c69ae5261950f8fff9bd258c0/src/CryptoNoteCore/BlockchainCache.cpp#L521-L525) are responsible for the log message seen above:
```cpp
uint32_t BlockchainCache::getTimestampLowerBoundBlockIndex(uint64_t timestamp) const {
  assert(!blockInfos.empty());

  auto& index = blockInfos.get<BlockIndexTag>();
  if (index.back().timestamp < timestamp) {
    // we don't have it
    throw std::runtime_error("no blocks for this timestamp, too large");
  }
// [...]
```

In the log file from ``Turtle?#3684`` I've seen that ``queryblockslite.bin`` was called with timestamp ``0``:
```
2018-Feb-06 17:50:25.433047 TRACE   [NodeRpcProxy] Send queryblockslite.bin request, timestamp 0
2018-Feb-06 17:50:25.474657 TRACE   [NodeRpcProxy] queryblockslite.bin failed: NodeErrorCategory:5, Internal node error
```

It is strange that the comparison above (``index.back().timestamp < timestamp``) is true, as ``timestamp`` is a ``uint64_t``. 

Another useful step would be to add logging for ``index.back().timestamp`` and ``timestamp`` in the code block above.

**Comment by deertacos** [comment] 2018-02-09 19:29
Reproduced again, stopped on a breakpoint, and grabbed those 2 values.
```index.back().timestamp``` 1518204227
```timestamp``` 1518204246

**Comment by deertacos** [comment] 2018-02-09 19:55
So, the error seems always to occur on the second call to ```getTimestampLowerBoundBlockIndex()```. (it's recursive)

When it happens, we passed through the first call, and recursed because ```index.back().timestamp == timestamp == index.front().timestamp```. I think all I need to do is change the conditional on [this code block](https://github.com/turtlecoin/turtlecoin/blob/49ca77c3c309375c69ae5261950f8fff9bd258c0/src/CryptoNoteCore/BlockchainCache.cpp#L527-L534) to be ``` if (index.front().timestamp <= timestamp)```? I'm going to try this, and see what happens.

**Comment by RocksteadyTC** [comment] 2018-02-12 01:41
**Fixed in 0.3.2**

**Closed by RocksteadyTC** 2018-02-12 01:41 UTC

**Comment by syserrr** [comment] 2018-02-20 22:42
I hate to bring this again , but I'm getting the same error with v0.3.2.1253


> 2018-Feb-21 00:35:57.719668 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:02.803812 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:07.924358 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:33.128563 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:38.168790 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:43.248399 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:36:58.374681 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:37:08.371921 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large
2018-Feb-21 00:37:33.571291 ERROR   [Core] Failed to query blocks: no blocks for this timestamp, too large

Ubuntu 16.04.2 LTS

**Comment by deertacos** [comment] 2018-02-20 22:55
Interesting... How do you make it happen? Same as before? Leaving it on for a long time?

I know I fixed the case that I found, so there is likely another cause of this error.

**Comment by syserrr** [comment] 2018-02-20 23:36
I've been running turtlecoind for about 8 hours , got this error three times,
I don't know if I can reproduce it , appears to show up randomly .

**Comment by deertacos** [comment] 2018-02-21 01:50
Does it adversely affect the daemon or wallet then? Or does it just happen a few times and go away? Because before it was creating a sort of soft-lock in the daemon.

**Comment by syserrr** [comment] 2018-02-21 11:46
I don't see that this error is crashing or preventing the daemon from working probably , No need to restart the daemon it just continue to work after showing that error , But I'm not sure about the wallet , I'll do more tests and report later.

**Comment by llawwehttam** [comment] 2018-03-19 13:52
I am also experiencing this issue again.

The Daemon no longer appears to fully lock up and the wallet is still able to query the daemon.

There doesn't appear to be a trigger and simply leaving the daemon open for a while causes the error to appear.

**Comment by RocksteadyTC** [comment] 2018-03-20 22:38
Sync a brand new chain from 0 after making sure you're running the latest compile from master.

**Comment by llawwehttam** [comment] 2018-03-25 00:55
I've compiled from master and synced from 0.

It's been running for a few hours and no issues yet. If it recurs I'll let you know.

**Comment by plavirudar** [comment] 2018-03-27 14:38
I can confirm that I also recently had the same issue, daemon is fine and continues mining blocks but wallet is unresponsive and spams the aforementioned error. 

I am attempting a fresh compile + resync now.
